### ISSUE TITLE
Option to use a remote coturn service?

### ISSUE THREAD

**Issue by decentral1se** [snikket-im/snikket-server#100]
Following recommendations in https://matrix-org.github.io/synapse/latest/turn-howto.html and experiences with running Snikket from home have shown that indeed, a coturn behind a NAT / port forwarding home setup is not very reliable. I didn't see this discussed anywhere yet and I know you're not super keen on making everything customisable but I would like to ask: is it possible already or do you see some possibility to make the coturn server optional? Because in the homebrew situation, it seems more reliable to point to an external coturn instance which has direct ipv4 entrypoint and no NAT/port fowarding.

**Comment by mwild1** [comment]
Hi! Good question. Yes, it's possible, and although there is no official how-to currently, the necessary configuration options are documented in the server admin guide we are building: https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/config.md#snikket_tweak_turnserver

Hope this helps!

**Comment by Menelmacar** [comment]
To the SNIKKET_TWEAK_TURNSERVER
There is one option missing to be able to fully change the turnserver. 
Would be good to have SNIKKET_TWEAK_TURNSERVER_PORT to change the default port of the turnserver.
