### ISSUE TITLE
Clarify via docs that multiple virtual hosts are not supported

### ISSUE THREAD

**Issue by decentral1se** [snikket-im/snikket-server#118]
One for the snikket.org FAQ perhaps (afaiu there is no public repo yet) and/or server docs.

**Comment by mwild1** [comment]
Not sure if this qualifies for the 'F' in 'FAQ' but it *has* come up a couple of times, so: https://snikket.org/faq/#q-can-i-host-more-than-one-domain-on-a-single-snikket-instance
