### ISSUE TITLE
mod_invites_api usage

### ISSUE THREAD

**Issue by nebulak** [snikket-im/snikket-server#12]
I am currently testing the invites API and found a small mistake in the documentation at https://modules.prosody.im/mod_invites_api. 
The command 

      prosodyctl mod_invites_api create example.com "My test key"

should be 

    prosodyctl mod_invites_api example.com create "My test key"

Thank's for developing snikket :+1:

**Comment by mwild1** [comment]
Hi! Thanks for the report, glad you like Snikket 🙂

The documentation is correct and applies to the version of the module in the Prosody community repository. Snikket is currently still using an earlier version (this applies to all the invite modules). They were written for Snikket first, and then made more generic and moved to prosody-modules.

The parameter order was switched for consistency with other similar commands in Prosody that accept a host. There may be other differences too.

At some point the plan is to move Snikket onto the Prosody modules, but it is not on the immediate roadmap while I'm working on larger tasks such as iOS.
