### ISSUE TITLE
Consider KUBERNETES support

### ISSUE THREAD

**Issue by jaylcm** [snikket-im/snikket-server#120]
Hi team,

Is snikket-server support in kubernetes environment?

Thanks

**Comment by decentral1se** [comment]
Not yet, I think there was some discussion about this on dev chat. It might be worth checking in about it. There are docker swarm configs floating around somewhere. 

PS. I would edit the title of this issue if I could, I perceive it was very "shout-y", perhaps "Consider kubernetes support" would be better.

**Comment by jaylcm** [comment]
> Not made for or tested with Kubernetes but this [pod specification](https://github.com/Zash/snikket-selfhosted/blob/podman/podman-compose.yml) file meant for use with podman might be of interest for experimentation or so.

Thanks for the sharing, I will try to deploy and configure in my staging environment.

**Comment by mwild1** [comment]
Thanks for the report, but there are no plans to officially support Kubernetes deployment at this time, so I'm going to close this issue. It doesn't mean Snikket can't run on Kubernetes, but my feeling is if you're managing Kubernetes you can probably figure out the rest :)
