### ISSUE TITLE
Fixing DNS records

### ISSUE THREAD

**Issue by shirtsvegan** [snikket-im/snikket-server#123]
I'm having the same issue as #27 but I am struggling to get the DNS records set correctly. I have looked through Namecheap docs but I'm not sure why it's not resolving corrrectly. Here are my current records in my DNS management through Namecheap:

[https://imgur.com/a/WrxFKDc](url)

I want to know if those are even set correctly because visiting share.chat.example.com in my browser points to nothing.

Any help would be appreciated, and then also help with doing the cert-refresh.sh command would also be beneficial too! Thanks

**Comment by mwild1** [comment]
Hi! Sure. Every DNS provider is slightly different (unfortunately), but I happen to be familiar with NameCheap's.

The record name, where you currently have `chat`, `groups` and `share` should be `chat` (unchanged), `groups.chat` and `share.chat`.

Hope this helps! Let us know if you have any trouble. We have a community chat: https://snikket.org/contact/
