### ISSUE TITLE
Use the Docker Hub image directly

### ISSUE THREAD

**Issue by EchedeyLR** [snikket-im/snikket-server#124]
Maybe I am wrong but I don't see instructions to use the Docker Hub containers directly instead of building our own through docker-compose.

I would be interested on it since I se watchower to upgrade my containers automatically.

**Comment by decentral1se** [comment]
Hi @EchedeyLR, https://github.com/snikket-im/snikket-server/blob/master/docker-compose.yml does use the Docker hub images directly. The install guide on the website doesn't ask you to build your own images, it uses this configuration above. If you want to run the images directly, you can `docker run ...` and gather what you need to provide manually from the above compose configuration.

**Comment by mwild1** [comment]
Also, although I wouldn't necessarily recommend it, you can certainly use Watchtower to update Snikket's images. Assuming a standard Watchtower setup, it should just work. You should still follow the usual Snikket setup instructions, though.

If you have any other issues, let us know!

**Comment by EchedeyLR** [comment]
I still don't know several things about docker so this is why I asked in the moment I saw the use of a docker-compose file.

Thank you both.
