### ISSUE TITLE
Netcat package missing on the web-portal container

### ISSUE THREAD

**Issue by fristihabeichnicht** [snikket-im/snikket-server#135]
After setting up snikket using docker-compose as per installation instructions, the snikket-portal container seems to be missing the netcat package. This causes docker's health checks to fail:
```
{
    "Start": "2022-05-08T19:41:21.877870615+02:00",
    "End": "2022-05-08T19:41:21.941432664+02:00",
    "ExitCode": 127,
    "Output": "/bin/sh: 1: nc: not found\n"
},

```
Manually installing the netcat package on the container fixes the problem, but that's hardly the clean solution. The container image should come with that package by default if it is intended to be used for these health checks.

**Comment by mwild1** [comment]
Hi, thanks for the report. This was fixed already in https://github.com/snikket-im/snikket-web-portal/pull/127 and will be in the next release.

The health checks are for informational purposes only, so other than the incorrect "unhealthy" display, no functionality was affected.
