### ISSUE TITLE
Update for jammy 

### ISSUE THREAD

**Issue by Nllii** [snikket-im/snikket-server#139]
update this line  for [Jammy Jellyfish](https://releases.ubuntu.com/22.04/
) or make a note so others can update it themselves in the future. 
https://github.com/snikket-im/snikket-server/blob/2c138cae3315d23722ab190eb06ca1cbea0cd10c/ansible/tasks/prosody.yml#L14

https://prosody.im/download/package_repository

If you came here from google. Don't forget about these files also.
https://github.com/snikket-im/snikket-server/blob/master/ansible/snikket.yml 

https://github.com/snikket-im/snikket-server/blob/master/ansible/files/prosody.cfg.lua

https://github.com/snikket-im/snikket-server/blob/2c138cae3315d23722ab190eb06ca1cbea0cd10c/Dockerfile#L1

**Comment by mwild1** [comment]
Hi, thanks for the report. I'm not exactly sure what issue you are experiencing.

Snikket uses Debian images, not Ubuntu. The release of Ubuntu 22.04 does not affect us or require any updates to our code that I'm aware of.

If you're aware of any incompatibility with running Snikket on Ubuntu, feel free to provide more information.
