### ISSUE TITLE
Allow configuring STUN/TURN port

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-server#147]
This can be useful to run multiple instances, avoid discovery and to bypass ISP blocks on the standard port.

- See also #143

**Comment by Zash** [comment]
I observe that mod_turn_external doesn't support multiple services, mod_external_services would be needed

**Comment by Zash** [comment]
I may be misunderstanding what "multiple instances" refers to then, thinking multiple TURN services.

**Comment by mwild1** [comment]
Ah, sorry, I see I said that. I meant that if you have another TURN service on the same machine being used for something else (and not using REST auth or whatever), it's a way to have Snikket's own TURN service not conflict with it (by changing the port). Snikket will only be using one service.

**Comment by ecker00** [comment]
Seems that this might be possible now?
https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/firewall.md

But I would be looking to disable the TURN server and instead set a custom one, as we already have a TURN server that can be used by multiple services.
