### ISSUE TITLE
Do not automatically create group chat for all circle members. 

### ISSUE THREAD

**Issue by gitbq** [snikket-im/snikket-server#149]
Currently when a new user registers, they are automatically joined to a group for whatever circle they are members.

Preferred behaviour:

1. Don't automatically join or show this group chat. 
2. Or have an option when creating the invitation, to include or not include the group chat.

**Comment by murtezayesil** [comment]
I would something that on surface looks similar to this. We should be able to create circle-less invitation links. Whoever using that link shouldn't be member of any circle and shouldn't inherit the contact list of any circle. It should be a blank slate.

Maybe only include the main admin's contact in the contacts list for a circleless account.
