### ISSUE TITLE
Option to accept self-signed from other users

### ISSUE THREAD

**Issue by muldjord** [snikket-im/snikket-server#154]
A friend is running a different XMPP server which he uses without issue. But, his server uses a self-signed certificate. When he tries to add me he gets the following message:
```
Remote server timeout.
A remote server or service specified as part or all of the JID of the
intended recipient (or required to fulfill a request) could not be
contacted within a reasonable amount of time.
Stream closed by peer: Your server's certificate is self-signed
(not-authorized)
```
I'm guessing that means my Snikket server won't allow communication with him due to the self-signed certificate.

Is it currently possible to configure my Snikket instance to allow this? If not, would you consider including it? I realize this could potentially be a security issue. But in this instance I know what I am doing so it would be nice to have this option.

Thank you for a great project.

**Comment by mwild1** [comment]
Hi, thanks for the report!

You're right. Snikket will only accept valid, trusted certificates. There is zero chance that we'll ever add a flag to accept arbitrary self-signed certificates, as this would be a massive security issue.

However, we are planning a federation control panel in the web interface in a future release. It's possible that after that, we could include a per-domain certificate fingerprint pinning thing. However that's getting quite advanced and even if you know what you are doing, most people would not. It's something I can think about.

In the meantime, encourage your friend to get a proper certificate. They're free and easy to obtain these days (e.g. from Let's Encrypt and others).

**Comment by muldjord** [comment]
Thank you for the reply. I tend to agree, so closing.
