### ISSUE TITLE
Implement management of user bookmarks via group membership (add/remove only)

### ISSUE THREAD

**Issue by horazont** [snikket-im/snikket-server#16]
Currently, we only send invitations. While that is nice and will pull in at least Snikket Android, it’s not perfect because it doesn’t allow clients which missed the invitation to join.

**Comment by distefam** [comment]
Documenting what was discussed in the general chat here for easy access...

On iOS, the client receives an invitation in the form of a push notification. If they do not accept it (even just dismissing the notification) there is no way to see that notification afterwards. Also, the private group chat associated with the circle does not display in the chats on the iOS client if an invitation has not been accepted on iOS, which differs from Android which automatically accepts the invitation.

**Comment by horazont** [comment]
Implemented in new [mod_groups_muc_bookmarks module](https://modules.prosody.im/mod_groups_muc_bookmarks.html); to be included in the next release.
