### ISSUE TITLE
Actually destroy private rooms upon deleting associated circle

### ISSUE THREAD

**Issue by distefam** [snikket-im/snikket-server#17]
When one deletes a circle from the admin dashboard the associated group chat still persists in client applications. While this may be desired, there is no indication that the group chat is no longer functional. Additionally, users may still send messages in the group chat.

Steps to reproduce:

1. Create a circle
2. Observe associated group chat in client
3. Delete circle
4. Observe associated group chat still in client
5. Successfully send messages within group chat

**Comment by horazont** [comment]
Destroy room != delete room. Fix on the way.

**Comment by distefam** [comment]
Additionally, invitations to the now destroyed room should be revoked if possible.

**Comment by horazont** [comment]
Fixed in https://hg.prosody.im/prosody-modules/rev/ca821df93cb9, will be in next server build.
