### ISSUE TITLE
Snikket push service configuration

### ISSUE THREAD

**Issue by ToxicMushroom** [snikket-im/snikket-server#176]
I found no documentation for this module, it seems to connect to `push.snikket.net` according to the prosody.cfg.lua ?
I assume this is related but I don't know how https://github.com/snikket-im/snikket-push-service.

My questions are the following:
 - Is this url configurable and if so how can a user self-host this service ?
 - Maybe some documentation on how the current notification push stuff works
 - Is this maybe made unnecessary by [mod_unified_push](https://modules.prosody.im/mod_unified_push) ?

**Comment by mwild1** [comment]
> Is this url configurable and if so how can a user self-host this service ?

The push service is related to the app, not to the server. The Snikket iOS app and the Snikket Android app (Play Store version only) use our push services. Other apps by other developers use their own. To use a self-hosted push service would require Apple/Google developer accounts, API keys and you would need to build your own apps from source.

> Maybe some documentation on how the current notification push stuff works

A bunch of this is documented here: https://snikket.org/app/privacy/

The underlying technical stuff is documented in XMPP's XEP-0357: https://xmpp.org/extensions/xep-0357.html

> Is this maybe made unnecessary by [mod_unified_push](https://modules.prosody.im/mod_unified_push)?

No. mod_unified_push is to allow [*other* apps](https://unifiedpush.org/users/apps/) to receive push notifications via XMPP. XMPP is already a real-time protocol and technically does not need push notifications, except to overcome mobile OS vendor restrictions (which Unified Push cannot overcome).
