### ISSUE TITLE
Update setup requirements

### ISSUE THREAD

**Issue by BluebonnetField** [snikket-im/snikket-server#177]
Docker-compose is built into docker now, and in theory should be a drop in replacement

https://github.com/snikket-im/snikket-server/blob/master/docs/setup/quickstart.md#step-2-docker

**Comment by mwild1** [comment]
Thanks for the report! With the new release I have updated the docs for 'docker compose'. One reason I had been holding back was because of some bugs in the newer implementation that some users had encountered, but I tested and they appear to be fixed now in recent versions.
