### ISSUE TITLE
Issue registering admin account on docker install, and port 5000 in use

### ISSUE THREAD

**Issue by AMoonRabbit** [snikket-im/snikket-server#204]
Hi all,

I have deployed the docker install on my server and setup nginx reverse proxy. I have setup an additional volume to mount the letsencrypt folder containing all the certs and bypass the cert manager container.

I can get the admin invite page to appear but when attempting to setup the user I get a long timeout and eventually a "server not found" message in the app. 

I noted also that the docker setup wants to use port 5000 and fails because it is already in use by my Funkwhale pod hosted on the same host. Is there a way I can tell Snikket to not use 5000? I don't see it in the config nor the proxy config.  I wonder if this is the cause of the issues I am having. 

Snikket Container Logs
```
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
socket: Protocol not supported
startup             info	Hello and welcome to Prosody version Snikket release beta.20220119.2
startup             info	Prosody is using the epoll backend for connection handling
portmanager         info	Activated service 'http' on [127.0.0.1]:5280
portmanager         info	Activated service 'https' on no ports
share.chat.udongein.reisen:http  info	Serving 'file_share' at https://share.chat.domain.com/upload
share.chat.udongein.reisen:tls   info	Certificates loaded
portmanager                      info	Activated service 's2s' on [*]:5269
portmanager                      info	Activated service 's2s_direct_tls' on no ports
portmanager                      error	Failed to open server port 5000 on *, this port is in use by another application
portmanager                      info	Activated service 'proxy65' on no ports
chat.udongein.reisen:http        info	Serving 'invites_register_api' at https://chat.domain.com/register_api
chat.udongein.reisen:http        info	Serving 'rest' at https://chat.domain.com/rest
mod_http                         info	Serving 'bosh' at https://chat.domain.com/http-bind
chat.udongein.reisen:http        info	Serving 'bosh' at https://chat.domain.com/http-bind
chat.udongein.reisen:http        info	Serving 'xep227' at https://chat.domain.com/xep227
portmanager                      info	Activated service 'c2s' on [*]:5222
portmanager                      info	Activated service 'c2s_direct_tls' on [*]:5223
portmanager                      info	Activated service 'legacy_ssl' on no ports
mod_http                         info	Serving 'websocket' at https://chat.domain.com/xmpp-websocket
chat.udongein.reisen:http        info	Serving 'websocket' at https://chat.domain.com/xmpp-websocket
chat.udongein.reisen:http        info	Serving 'host_status_check' at https://chat.domain.com/host_status_check
chat.udongein.reisen:tls         info	Certificates loaded
chat.udongein.reisen:http        info	Serving 'files' at https://chat.domain.com/
chat.udongein.reisen:http        info	Serving 'invites_api' at https://chat.domain.com/invites_api
chat.udongein.reisen:http        info	Serving 'altconnect' at https://chat.domain.com/.well-known
chat.udongein.reisen:cloud_notify  info	Module loaded
chat.udongein.reisen:http          info	Serving 'oauth2' at https://chat.domain.com/oauth2
chat.udongein.reisen:http          info	Serving 'admin_api' at https://chat.domain.com/admin_api
groups.chat.udongein.reisen:tls    info	Certificates loaded
mod_cron                           info	Running periodic tasks
```

**Comment by AMoonRabbit** [comment]
Okay, issues with signing into a client were port related as I hadn't forwarded the required ports on my router....

But I still need to change Prox65 FTP port if possible.

**Comment by mwild1** [comment]
Hi, thanks for the report. Glad you got the cert issues sorted.

I've retitled the issue to be about adding a configuration option for the proxy65 port, which shouldn't be too hard. Lack of proxy65 shouldn't affect things generally, except the ability to transfer large files (over 100MB).

**Comment by AMoonRabbit** [comment]
Good to know it's not really going to affect anything. I doubt I will be sending anything that large anytime soon and if need be there are ways around that. 

Thanks for the update.

**Comment by tctlrd** [comment]
What is the "socket: Protocol not supported" message about? I also get a stream of those on startup.

**Comment by AMoonRabbit** [comment]
> What is the "socket: Protocol not supported" message about? I also get a stream of those on startup.

If I recall, socket errors are related to architecture incompatibility, I'm running the container on a pi 4b so it's Arm64 based.

**Comment by Zash** [comment]
https://github.com/coturn/coturn/issues/492 seems a likely candidate

**Comment by tctlrd** [comment]
I am running Snikket in podman on the latest AlmaLinux. It seems SCTP is not included:  
[How to setup SCTP In Red Hat Enterprise Linux 8](https://access.redhat.com/solutions/6625041) ( https://access.redhat.com/solutions/6625041 )  
Should I bother setting up SCTP for Snikket?

**Comment by AMoonRabbit** [comment]
> I am running Snikket in podman on the latest AlmaLinux. It seems SCTP is not included in RHEL/Alma: [How to setup SCTP In Red Hat Enterprise Linux 8](https://access.redhat.com/solutions/6625041) ( https://access.redhat.com/solutions/6625041 ) Should I bother setting up SCTP for Snikket?

This issue is closed so it would be better to raise a new issue for that specially as my issue is actually resolved.
