### ISSUE TITLE
systemd startup file

### ISSUE THREAD

**Issue by kkretsch** [snikket-im/snikket-server#21]
For restarting all services on OS reboot I added this file **/etc/systemd/system/snikket.service** for systemd. Feel free to integrate it somehow.

```
[Unit]
Description=Snikket service
After=docker.service
Requires=docker.service

[Service]
User=root
Group=root
TimeoutStartSec=0
RestartSec=10
Restart=always
WorkingDirectory=/etc/snikket
ExecStartPre=-/usr/local/bin/docker-compose down
ExecStart=/usr/local/bin/docker-compose up
ExecStop=/usr/local/bin/docker-compose down

[Install]
WantedBy=multi-user.target
```

**Comment by mwild1** [comment]
Hi, thanks for this. I should test, but the current docker-compose *should* already take care of restarting containers after a reboot. See https://docs.docker.com/compose/compose-file/compose-file-v3/#restart for more info.

Generally if we can do it with docker-compose, that's one less thing for admins to worry about.
