### ISSUE TITLE
Could the getting started bit on the website include support for reverse-proxies and ports?

### ISSUE THREAD

**Issue by driftywinds** [snikket-im/snikket-server#227]
I have multiple services running on different ports on my VPS and would like to setup snikket with docker-compose such that the containers have configurable ports as endpoints that I can reverse proxy through caddy, (and thus not work around snikket hogging the :80 port for itself).

Is this possible? and if yes, how do I configure it in the docker-compose.yml file?

Would appreciate this being added into the getting-started part on the website too.

**Comment by mwild1** [comment]
Hi! Sure, you can find information about running Snikket behind a reverse proxy here: https://snikket.org/service/help/advanced/reverse_proxy/

It's linked to from the quickstart guide, though maybe it needs to be more prominent (as it already is in [this version of the guide](https://snikket.org/service/help/setup/quickstart/)).

If you need any help with the setup, there are many experienced (and new) self-hosters you can find in our [chat channel](https://snikket.org/contact/).

Good luck with your Snikket adventure!

**Comment by driftywinds** [comment]
> Hi! Sure, you can find information about running Snikket behind a reverse proxy here: https://snikket.org/service/help/advanced/reverse_proxy/
> 
> It's linked to from the quickstart guide, though maybe it needs to be more prominent (as it already is in [this version of the guide](https://snikket.org/service/help/setup/quickstart/)).
> 
> If you need any help with the setup, there are many experienced (and new) self-hosters you can find in our [chat channel](https://snikket.org/contact/).
> 
> Good luck with your Snikket adventure!

Thanks a ton!
