### ISSUE TITLE
Question on how to make server work specifying the subdomains, for a case like DuckDNS

### ISSUE THREAD

**Issue by nyakojiru** [snikket-im/snikket-server#228]
Hello, I was wondering if there is a way to install the Snikket server and use duckdns.org (which is free DNS). The problem is that it is already a subdomain, and you can't create sublevels of them. Maybe there is a way to specify the DNS for groups and share?
Example:
chat.example.com
groups.example.com
share.example.com

**Comment by mwild1** [comment]
Hi there!

DuckDNS does not support creating "sub-sub-domains", but they do work :) They will just always point to the same IP address as your main domain. This means they *will* work with Snikket.

So you just set the IP of the main domain correctly, and then follow the rest of the instructions. You don't need to add anything in DNS for groups and share - DuckDNS will do it automatically for you.

Hope this helps!
