### ISSUE TITLE
Make groupchats more configurable

### ISSUE THREAD

**Issue by rototom** [snikket-im/snikket-server#24]
I'd like to invite users of other xmpp servers to my groupchat on my snikket server. I don't seem to be allowed to do this? gajim does not let me configure the chatroom.

**Comment by mwild1** [comment]
Hi, sorry for the very delayed response to this. I suspect you were trying to modify the configuration of one of the default group chats that Snikket creates, linked to circles.

You can create as many normal group chats as you want, and configure and invite however you wish.
