### ISSUE TITLE
Cannont send pictures

### ISSUE THREAD

**Issue by wilecoyote2019** [snikket-im/snikket-server#27]
Hi,
I installed snikket server on Debian 10 following instructions provided in the Quick Guide. 
Server is working fine, I can chat with firends correctly but each time I try to send a picture it fails. 

Is there any way to look at a log file to see what is happening ?

Thanks!

**Comment by mwild1** [comment]
Hi! Glad you got it (mostly) working ok. Strange about sharing pictures.

Send a picture. When it fails, long-press on it until a menu pops up. Select to show the error. Let me know what it says, hopefully it will provide a clue 🙂

**Comment by wilecoyote2019** [comment]
Oh thank you very much! Yes I see now :) "Unable to resolve share.chat.myserver.com. No address is associated with hostname" 
(chat.myserver.com is not my real server I've replaced it in the message). The url   share.chat.myserver.com is supposed to resolve to chat.myserver.com ? 
It was not indicated in the quick start guide to resolve this adddress or I missed some part ?
Thanks for your help!

**Comment by mwild1** [comment]
As well as chat.example.com two additional DNS records are required - check https://snikket.org/service/quickstart/#step-1-dns

After setting up the DNS records you will probably need to re-fetch certificates for those domains. Run the three docker commands from here: https://github.com/snikket-im/snikket-selfhosted/blob/main/scripts/cert-refresh.sh

Good luck! :)

**Comment by wilecoyote2019** [comment]
Yes i was going too fast! I missed this part! Thank you very much. Great server easy to install. Great app and great job!

**Comment by mwild1** [comment]
Excellent! Happy chatting! 🙂

**Comment by wilecoyote2019** [comment]
Just one thing, 
I launched the dockers commands from  here : 
https://github.com/snikket-im/snikket-selfhosted/blob/main/scripts/cert-refresh.sh

This one is not correct (at least on Debian 10) : 
docker exec -it snikket-proxy service reload nginx 

It should be : 
docker exec -it snikket-proxy service nginx reload

But maybe on other systems the syntax is different...

**Comment by mwild1** [comment]
Right you are, thanks for catching that! Fixed in https://github.com/snikket-im/snikket-selfhosted/commit/c8e3ee0cd56e2280ea1ee7a80eca6d38baebf9b3
