### ISSUE TITLE
Allow to backup Snikket

### ISSUE THREAD

**Issue by KillianKemps** [snikket-im/snikket-server#3]
Hello,

I installed Snikket on a server and also installed the Snikket app through F-Droid. It all worked well.

I know Snikket is still on Alpha, but is it possible to allow backups?

To do this I think we should make the Docker volume available on the host. What is required to be backed up? On [Prosody's documentation](https://prosody.im/doc/backups) I read `/etc/prosody`, but maybe as Snikket already configures everything it is not needed and `/var/lib/prosody` is empty in the container.

However, there is plenty of files in `/snikket`. Should we backup this entire folder? Or maybe only subfolders like `/snikket/prosody/chat.example.com/accounts`?

I have never managed a XMPP server, but I think the only important thing is to have the accounts backed up in order to avoid users to have to register themselves again.

For the moment I will configure the backups myself with Restic for `/etc/prosody` and entire `/snikket` folder.

**Comment by mwild1** [comment]
There is an example script for this now over at https://github.com/snikket-im/snikket-selfhosted/blob/main/scripts/backup.sh :+1:
