### ISSUE TITLE
Bad certificate share.chat.xxx.org

### ISSUE THREAD

**Issue by lagemeet** [snikket-im/snikket-server#36]
Bad certificate share.chat.xxx.org
 i can't send any images because snikket use wrong certificate for http upload.

![image](https://user-images.githubusercontent.com/80648740/111083815-008ecd00-8518-11eb-8c98-76cc4416ca21.png)

![image](https://user-images.githubusercontent.com/80648740/111083801-e9e87600-8517-11eb-9b35-691a153e3996.png)

**Comment by lagemeet** [comment]
Sorry i missed a  #27 issue 
Perfect server and perfect app :)

**Comment by mwild1** [comment]
Glad you got it figured out! 🙂
