### ISSUE TITLE
Design and/or implement restrictions for prosody:restricted users

### ISSUE THREAD

**Issue by horazont** [snikket-im/snikket-server#37]
In https://github.com/snikket-im/snikket-web-portal/issues/42, support for changing roles of users was implemented in the web portal. Now we "just" need to make that do anything beyond admin vs. normal.

What restrictions should prosody:restricted users have? Where and how should they be enforced?

**Comment by mwild1** [comment]
Planned restrictions:

- Restricted users should not be allowed federation access (some services will always be allowed, such as push services)
- Restricted users should not be allowed to invite new users, even when invitations by users are enabled by the admin (#58)
- Restricted users should not be allowed to create public channels
