### ISSUE TITLE
Manage accounts through Web interface

### ISSUE THREAD

**Issue by KillianKemps** [snikket-im/snikket-server#4]
Currently we need to create invitations through the command line.
As there is already a web page online, it could be more practical to allow admin users to log in into the Web interface and to manage users through it.

It could allow admin users to create accounts while being away from their computers, just with a simple smartphone for example, and share links with people while being talking about Snikket instead of having to come home and SSH to the server.

Or maybe is it already possible on the Snikket mobile app?

**Comment by horazont** [comment]
The next release (due tomorrow) will have that, it will include https://github.com/snikket-im/snikket-web-portal/. Stay tuned [on the blog](https://snikket.org/blog/).

**Comment by mwild1** [comment]
Released! :tada:
