### ISSUE TITLE
Reverse proxy guide does not properly handle HTTP/HTTPS

### ISSUE THREAD

**Issue by horazont** [snikket-im/snikket-server#41]
The nginx reverse proxy guide proxies to the HTTP port only. This may cause a redirect loop because the built-in snikket proxy will try to redirect to HTTPS.

To make this work easily, we should update the guide to use:

```
  location / {
      proxy_pass https://localhost:5443/;
      proxy_set_header  Host            $host;
      proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
      # REMOVE THIS IF YOU CHANGE `localhost` TO ANYTHING ELSE ABOVE
      proxy_ssl_verify              off;
      proxy_set_header X_FORWARDED_PROTO https;
      proxy_ssl_server_name on;
  }
```

for the SSL sections.

**Comment by mwild1** [comment]
Bundling a separate docs issue into this one: we should also document how to set the appropriate request size limits, such as `client_max_body_size` in nginx so that HTTP upload can still work reliably.

**Comment by mwild1** [comment]
and another issue, this sentence is missing the word "intercept":

> Be careful that your reverse proxy does not requests from Let's Encrypt that are intended for the Snikket service.

**Comment by horazont** [comment]
@mwild1 I cannot assign myself, but I’ll prepare a PR for this.
