### ISSUE TITLE
Enable IPv6 by default if possible

### ISSUE THREAD

**Issue by mwild1** [snikket-im/snikket-server#56]
This issue is to track enabling IPv6 by default in the snikket-server image. It can currently be enabled by setting the environment variable `SNIKKET_TWEAK_IPV6=1`.

There are some hurdles. Docker does not enable IPv6 by default, which means it will be broken unless the admin explicitly enables it. This probably (hopefully?) doesn't affect host network mode, which is currently in use but changing this back has been discussed, e.g. in https://github.com/snikket-im/snikket-web-portal/pull/72

Another consideration is lack of "happy eyeballs" support in Prosody. Certain network configuration issues/malfunctions may cause undesirable user experiences with federation. I think work on this should be prioritized.

**Comment by mwild1** [comment]
We have happy eyeballs in Prosody now, and we have no immediate plans to switch away from host network mode. IPv6 by default?

**Comment by Zash** [comment]
IPv6 by default!

**Comment by Zash** [comment]
What concretely is there to do here? Switch default for `SNIKKET_TWEAK_IPV6` or remove completely?

**Comment by mwild1** [comment]
I think allowing it by default, but still allowing it to be disabled (as we should consider for IPv4 if not already).
