### ISSUE TITLE
Disable features Message Archive Management

### ISSUE THREAD

**Issue by vncloudsco** [snikket-im/snikket-server#64]
I have checked the server information, I would like to ask some way to disable features. 
- I want to disable the feature Message Archive Management
- I want to enable the feature Security Labels in XMPP

![image](https://user-images.githubusercontent.com/41409442/133806502-7f3d9896-56eb-405c-b352-4bcbebe34cd6.png)

**Comment by mwild1** [comment]
Hi, thanks for the request! Unfortunately neither of these changes fit with the Snikket [roadmap and goals](https://snikket.org/about/goals/).

- Disabling Message Archive Management would cause conversations to not be synchronized across a user's devices, and it may even cause messages to be lost under certain circumstances. This would negatively impact the user experience and reliability of the system.
- Security Labels are an advanced and specialized feature that do not fit into a personal messaging application for general use.

If you need this level of customization, you should probably explore other options for XMPP that can be tailored to your specific needs. For example Snikket uses Prosody, and other server software is available such as ejabberd and Tigase.

Hope this helps!
