### ISSUE TITLE
Caddy support

### ISSUE THREAD

**Issue by turguenev** [snikket-im/snikket-server#82]
Hi. Please, add support and instructions to the reverse proxy section for Caddy web server. 

Caddy is a web server commonly used by self-hosters. After trying for a few days, I have not been able to make it work with snikket. 

Caddy: 
- https://github.com/caddyserver/caddy
- https://caddyserver.com/
- Documentation https://caddyserver.com/docs/

**Thank you for your work and effort. Snikket is a great project**

**Comment by mwild1** [comment]
Hi, thanks for the report! I've never used Caddy, but I posted this to our community chat in the hope that someone familiar could offer to write documentation supporting this setup.

If nobody steps up, I'll try to take a look at it after I've wrapped the upcoming release :)

**Comment by Rijul-A** [comment]
#87 adds a reverse proxy guide for Caddy. Let me know what you think
