### ISSUE TITLE
Snikket on a RaspberryPi

### ISSUE THREAD

**Issue by TilmanJimenez** [snikket-im/snikket-server#9]
When I try to run the container on a raspberry I get "Error response from daemon: Container is restarting, wait until the container is running". `docker logs --tail 50 --follow --timestamps snikket` returns "exec user process caused: exec format error". Googling a bit it seems that happens when you're trying to run adm packages on arm. Im just confused as the quick setup explicitly says "For the server [...] you can use a physical device such as a Raspberry Pi." Is the raspberry not supported yet?

**Comment by deckname** [comment]
I ran into the same problem

**Comment by horazont** [comment]
@deckname @TilmanJimenez The [new release from two days ago](https://snikket.org/blog/feb-2021-server-release/) brings support for Raspberry Pi setups.

**Comment by mwild1** [comment]
Yep, thanks for your patience. Setting up the build system to produce ARM images took longer than expected :)
