### ISSUE TITLE
Q: Any security recommendation?

### ISSUE THREAD

**Issue by xcme** [snikket-im/snikket-server#94]
Hi all,

I just installed snikket and after containers upgrade the problem I had in #61 has been solved. Snikket works and looks fine.
The only questions I have now:
- Are there some security recommendation I can apply after installation? For example:
a) redirect http to https in nginx
b) close some ports via iptables
c) tune docker-compose.xml in order to limit interfaces for listening
and so on...

Or the basic installation is quite safe and I have nothing to worry about?

Thanks

**Comment by mwild1** [comment]
The standard installation is designed to be safe by default (the point of Snikket after all is to make it easy to host for people who may be new to self-hosting).

Snikket already has a HTTP->HTTPS redirect. The necessary ports you need are listed in the [firewall documentation](https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/firewall.md).

We don't currently add HTTPS HSTS headers, though this is under consideration for a future release. In the meantime you may want to add these in your reverse proxy, [per this guide](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/). It adds an extra layer of protection when accessing the web interface.

The docker-compose file should generally not be modified, Snikket must be internet-accessible to ensure that various features work (certificates, push notifications, and so on).

As there are no known issues with the default Snikket installation, the next most important thing from a security perspective would be to update quickly if a security update is released in the future. Snikket has a built-in mechanism enabled by default that will send you (all configured admin accounts) a message if there is an update available (it will also tell you if it is a security update or not).

You should also make sure the server that Snikket is running on is secure. If you run other services on the same server, ensure these are all up to date with security releases as well. If you're on Debian/Ubuntu, setting up 'unattended-upgrades' is a good idea. There are also security audit tools such as 'lynis' which will run a bunch of system checks and give you advice about what you could tighten up.

Hope this helps!
